### ISSUE TITLE
start bot with linux cron. incorrect paths

### ISSUE THREAD

**Issue by markotpiotr** [linkfy/Tools-for-Instagram#15]
there is a small problem when starting the bot with crontab. database, account and other paths are invalid. should be corrected or give the opportunity to indicate their own

**Comment by linkfy** [comment]
Hey markotpiotr, the app will  take the current directory to run the some important stuff, thats why on the documentation the paths are written as "node bots/mybot.js", I recommend to use the root folder of the TFI project to do that stuff, instead of calling from crontab I recommend to call an intermediate Javascript process manager like PM2 or Nodemon to take control of that behavior.

**Comment by markotpiotr** [comment]
Thank you for the quick reply :) I will use pm2.
